# Generated by Django 5.2.6 on 2025-09-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvgcontrolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expired_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
